"""Scan ``input/classified_csv/`` and emit ``classifier/config/type_enum.py``.

The generated module is the source of truth for the 3-letter ``type``
enum used by the classifier. Known codes are synced with the existing
``TYPE_TO_BUCKET`` map; outliers (codes seen in CSVs but not in the
known map) are emitted in a separate ``OBSERVED_OUTLIERS`` dict so a
human can decide whether to add them to ``TYPE_TO_BUCKET`` later.

Run from project root::

    build-type-enum
"""
from __future__ import annotations

import datetime as dt
from collections import Counter
from pathlib import Path

import pandas as pd

from classifier.config.buckets import TYPE_TO_BUCKET
from classifier.io.normalize import is_empty

CSV_ROOT = Path("input/classified_csv")
OUT_PATH = Path("src/classifier/config/type_enum.py")


def _collect_types() -> tuple[Counter[str], int]:
    counts: Counter[str] = Counter()
    csv_paths = sorted(CSV_ROOT.rglob("*.csv"), key=lambda p: str(p).lower())
    for csv_path in csv_paths:
        df = pd.read_csv(csv_path, dtype=str, keep_default_na=False, na_values=[])
        if "type" not in df.columns:
            continue
        for value in df["type"]:
            if is_empty(value):
                continue
            counts[str(value).strip().upper()] += 1
    return counts, len(csv_paths)


def _render(counts: Counter[str], n_csvs: int) -> str:
    known = sorted(TYPE_TO_BUCKET.keys())
    outliers = sorted(k for k in counts if k not in TYPE_TO_BUCKET)
    today = dt.date.today().isoformat()

    lines = [
        '"""Generated by ``build-type-enum``. Do not edit by hand."""',
        "from __future__ import annotations",
        "",
        f"# Generated {today} from {n_csvs} CSV(s) under input/classified_csv/.",
        "",
        "KNOWN_TYPES: frozenset[str] = frozenset({",
    ]
    for code in known:
        lines.append(f"    {code!r},")
    lines.append("})")
    lines.append("")
    lines.append("OBSERVED_OUTLIERS: dict[str, int] = {")
    for code in outliers:
        lines.append(f"    {code!r}: {counts[code]},")
    lines.append("}")
    lines.append("")
    lines.append("ALL_OBSERVED_TYPES: frozenset[str] = KNOWN_TYPES | frozenset(OBSERVED_OUTLIERS)")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not CSV_ROOT.exists():
        raise SystemExit(f"csv dir not found: {CSV_ROOT} (run convert-classified first)")
    counts, n_csvs = _collect_types()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(_render(counts, n_csvs), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH}")
    print(f"  KNOWN_TYPES: {len(TYPE_TO_BUCKET)}")
    print(f"  OBSERVED_OUTLIERS: {sum(1 for k in counts if k not in TYPE_TO_BUCKET)}")
    print(f"  total distinct types in CSVs: {len(counts)}")


if __name__ == "__main__":
    main()
