"""Generate ``classifier.config.type_to_discipline`` from labeled CSVs.

For each known document type (3-letter code), this tool counts how many
labelled rows of that type fell into each DEST discipline (after applying
the client -> DEST fold). When a single DEST discipline accounts for at
least ``MAJORITY_FLOOR`` of a type's labelled rows, the type is emitted
as a hint that boosts that discipline's score at classify time.

Conservative by design: types whose label distribution is split (no
clear majority) are simply omitted from the mapping rather than nudging
the classifier in an ambiguous direction.

Run from project root::

    learn-type-discipline
"""
from __future__ import annotations

import datetime as dt
from collections import Counter, defaultdict
from pathlib import Path

import pandas as pd

from classifier.config.type_enum import KNOWN_TYPES
from classifier.io.normalize import is_empty
from classifier.tools.learn_discipline_keywords import (
    DISCIPLINE_FOLD_CSV, DISCIPLINES_TABLE_CSV,
    _load_fold, _load_valid_dest_ids, _parse_discipline,
)

CSV_ROOT = Path("input/classified_csv")
OUT_PATH = Path("src/classifier/config/type_to_discipline.py")

MAJORITY_FLOOR: float = 0.70
MIN_TYPE_OCCURRENCES: int = 4


def _collect_pairs(fold: dict[int, int]
                   ) -> tuple[dict[str, Counter[int]], Counter[int]]:
    """Return ``(per_type_counts, orphans)`` where
    ``per_type_counts[type]`` is a Counter of DEST discipline ids."""
    per_type: dict[str, Counter[int]] = defaultdict(Counter)
    orphans: Counter[int] = Counter()
    for p in sorted(CSV_ROOT.rglob("*.csv"), key=lambda x: str(x).lower()):
        df = pd.read_csv(p, dtype=str, keep_default_na=False, na_values=[])
        if not {"type", "discipline_id"}.issubset(df.columns):
            print(f"  [skip] {p}: missing 'type' or 'discipline_id' column")
            continue
        for _, row in df.iterrows():
            t = str(row["type"]).strip().upper()
            if not t or t not in KNOWN_TYPES:
                continue
            client_disc = _parse_discipline(row["discipline_id"])
            if client_disc is None:
                continue
            dest_disc = fold.get(client_disc)
            if dest_disc is None:
                orphans[client_disc] += 1
                continue
            per_type[t][dest_disc] += 1
    return per_type, orphans


def _decide_mappings(per_type: dict[str, Counter[int]]
                     ) -> tuple[dict[str, tuple[int, float, int]],
                                 dict[str, tuple[int, float, int]]]:
    """Return ``(emitted, ambiguous)`` keyed by type.

    Each value is ``(dest_id, share, total_count)`` so the generated
    config can show the supporting evidence.
    """
    emitted: dict[str, tuple[int, float, int]] = {}
    ambiguous: dict[str, tuple[int, float, int]] = {}
    for t, dist in per_type.items():
        total = sum(dist.values())
        if total < MIN_TYPE_OCCURRENCES:
            continue
        winner, win_count = dist.most_common(1)[0]
        share = win_count / total
        if share >= MAJORITY_FLOOR:
            emitted[t] = (winner, share, total)
        else:
            ambiguous[t] = (winner, share, total)
    return emitted, ambiguous


def render(emitted: dict[str, tuple[int, float, int]],
           ambiguous: dict[str, tuple[int, float, int]],
           source_root: Path) -> str:
    now = dt.datetime.now(dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = []
    lines.append('"""Generated by ``learn-type-discipline``. Do not edit by hand.')
    lines.append("")
    lines.append(f"Source: {source_root.as_posix()}/**/*.csv")
    lines.append(f"Generated: {now}")
    lines.append(f"Majority floor: {MAJORITY_FLOOR:.0%}; min occurrences: {MIN_TYPE_OCCURRENCES}")
    if ambiguous:
        lines.append("")
        lines.append("Ambiguous types (no clear majority -- not emitted):")
        for t in sorted(ambiguous):
            d, share, total = ambiguous[t]
            lines.append(f"  {t}: top dest_id={d} share={share:.0%} of {total} rows")
    lines.append('"""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("# Each entry: type -> (dest_discipline_id, share, support_count)")
    lines.append("# share and support_count are informational; only dest_id is used at classify time.")
    lines.append("TYPE_TO_DISCIPLINE: dict[str, int] = {")
    for t in sorted(emitted):
        d, share, total = emitted[t]
        lines.append(f"    {t!r}: {d},  # {share:.0%} of {total} rows")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not CSV_ROOT.exists():
        raise SystemExit(f"csv dir not found: {CSV_ROOT}")
    valid_dest_ids = _load_valid_dest_ids()
    fold = _load_fold(valid_dest_ids)
    per_type, orphans = _collect_pairs(fold)
    emitted, ambiguous = _decide_mappings(per_type)
    text = render(emitted, ambiguous, CSV_ROOT)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH}")
    print(f"  fold table:        {DISCIPLINE_FOLD_CSV}")
    print(f"  types observed:    {len(per_type)}")
    print(f"  types emitted:     {len(emitted)}")
    print(f"  types ambiguous:   {len(ambiguous)}")
    if orphans:
        orphan_summary = ", ".join(f"{d} ({n})" for d, n in orphans.most_common())
        print(f"  client IDs dropped (no fold entry):")
        print(f"    {orphan_summary}")
    if emitted:
        print(f"  sample emissions:")
        for t in sorted(emitted)[:5]:
            d, share, total = emitted[t]
            print(f"    {t} -> dest_id={d}  ({share:.0%} of {total} rows)")


if __name__ == "__main__":
    main()
