"""Generated by ``learn-discipline-keywords``. Do not edit by hand.

Source: input/classified_csv/**/*.csv
Generated: 2026-05-25T07:56:32Z
Training rows used: 559
"""
from __future__ import annotations

UNTRAINED_DISCIPLINES: frozenset[int] = frozenset({
})

DISCIPLINE_KEYWORDS: dict[int, tuple[tuple[str, float], ...]] = {
    1: (
        ('NOTES', 2.8904),
        ('CALCULATION NOTES', 2.7081),
        ('FOUNDATION', 2.4849),
        ('MISC', 1.9459),
        ('RACK', 1.9459),
        ('LAYOUT PLAN', 1.6679),
        ('MISC PIPE', 1.6094),
        ('PIPE RACK', 1.6094),
        ('TOPOGRAPHICAL', 1.6094),
        ('FOUNDATION DETAILS', 1.3863),
    ),
    4: (
        ('METHOD', 4.2047),
        ('METHOD STATEMENT', 4.2047),
        ('STATEMENT', 4.2047),
        ('PROCEDURE', 3.5089),
        ('PIPING LAYOUT', 3.2189),
        ('DISPOSAL TANK', 3.0995),
        ('WATER DISPOSAL TANK', 3.0995),
        ('TANK', 3.061),
        ('ELECTRICAL', 2.9957),
        ('NO', 2.8332),
    ),
    7: (
        ('TRANSMITTERS', 1.9459),
        ('ICSS', 1.6094),
        ('MULTIPHASE FLOW', 1.6094),
        ('MULTIPHASE FLOW METER', 1.6094),
        ('ACTING', 1.3863),
        ('ACTING REGULATORS', 1.3863),
        ('AREA FLOWMETER', 1.3863),
        ('DEVICES', 1.3863),
        ('ELECTRONIC', 1.3863),
        ('ELECTRONIC TRANSMITTERS', 1.3863),
    ),
    11: (
        ('INSTRUMENT DIAGRAM', 3.2581),
        ('PIPING & INSTRUMENT', 3.2189),
        ('DIAGRAM', 2.7789),
        ('HEADER', 2.7726),
        ('HEADER SAHIL', 2.7726),
        ('HEADER SAHIL CDS', 2.7726),
        ('DIAGRAM WATER', 2.7081),
        ('PROCESS', 2.6391),
        ('DIAGRAM WATER DISPOSAL', 2.3979),
        ('FLARE', 2.1972),
    ),
}
