"""Generated by ``learn-discipline-keywords``. Do not edit by hand.

Source: input/classified_csv/**/*.csv
Generated: 2026-05-25T06:29:30Z
Training rows used: 339
"""
from __future__ import annotations

UNTRAINED_DISCIPLINES: frozenset[int] = frozenset({
})

DISCIPLINE_KEYWORDS: dict[int, tuple[tuple[str, float], ...]] = {
    1: (
        ('NOTES', 2.8904),
        ('CALCULATION NOTES', 2.7081),
        ('FOUNDATION', 2.4849),
        ('LAYOUT PLAN', 1.9459),
        ('MISC', 1.9459),
        ('RACK', 1.9459),
        ('STEEL STRUCTURE', 1.9459),
        ('STRUCTURE', 1.9459),
        ('CALCULATION', 1.7233),
        ('MISC PIPE', 1.6094),
    ),
    4: (
        ('CDS', 3.7093),
        ('TANK', 3.5967),
        ('SAHIL', 3.5105),
        ('PIPING', 3.4965),
        ('SAHIL CDS', 3.4545),
        ('DISPOSAL TANK', 3.4538),
        ('WATER DISPOSAL TANK', 3.4538),
        ('DISPOSAL', 3.3457),
        ('WATER', 3.3457),
        ('WATER DISPOSAL', 3.3457),
    ),
    7: (
        ('INSTRUMENT', 2.6391),
        ('TRANSMITTERS', 1.9459),
        ('FLOW', 1.6094),
        ('FLOW METER', 1.6094),
        ('ICSS', 1.6094),
        ('METER', 1.6094),
        ('MULTIPHASE', 1.6094),
        ('MULTIPHASE FLOW', 1.6094),
        ('MULTIPHASE FLOW METER', 1.6094),
        ('SHUTDOWN', 1.6094),
    ),
}
