"""Generated by ``learn-type-keywords``. Do not edit by hand.

Source: input/classified_csv/**/*.csv
Generated: 2026-05-13T18:22:54Z
Training rows used: 256

Untrained types (< 4 examples, no rules emitted):
  BOD (2), BOM (1), DBD (2), DCE (2), DHZ (1), DPP (3), DSD (3), DWD (1), IDX (1), MTO (2), PHL (3), PLN (1), PRO (3), PSF (3), REG (1), SOW (2)
"""
from __future__ import annotations

UNTRAINED_TYPES: frozenset[str] = frozenset({
    'BOD',
    'BOM',
    'DBD',
    'DCE',
    'DHZ',
    'DPP',
    'DSD',
    'DWD',
    'IDX',
    'MTO',
    'PHL',
    'PLN',
    'PRO',
    'PSF',
    'REG',
    'SOW',
})

TYPE_KEYWORD_RULES: dict[str, tuple[tuple[str, float], ...]] = {
    'CAL': (
        ('CALCULATION', 1.9459),
        ('CALCULATION NOTE', 1.0986),
        ('NOTE', 1.0986),
        ('STRUCTURAL CALCULATION', 1.0986),
        ('STRUCTURAL CALCULATION NOTE', 1.0986),
    ),
    'DAL': (
        ('LAYOUT AREA', 2.1972),
        ('STEEL STRUCTURE', 2.1972),
        ('STRUCTURE', 2.1972),
        ('2407/2408', 2.0794),
        ('P 2407/2408', 2.0794),
        ('PUMPS P 2407/2408', 2.0794),
        ('STEEL', 2.0723),
        ('LAYOUT', 1.9866),
        ('ARRANGEMENT', 1.9459),
        ('ARRANGEMENT LAYOUT', 1.9459),
    ),
    'DAS': (
        ('DATA', 3.1738),
        ('DATA SHEET', 3.1738),
        ('SHEET', 3.0604),
        ('ELECTRICAL DATA', 1.3863),
        ('ELECTRICAL DATA SHEET', 1.3863),
        ('PRESSURE', 1.3863),
        ('/ 2408', 1.0986),
        ('01 FT', 1.0986),
        ('01 FT 0605', 1.0986),
        ('01 P', 1.0986),
    ),
    'DGA': (
        ('LAYOUT DRAWING', 2.5649),
        ('PIPING LAYOUT DRAWING', 2.5649),
        ('PIPING LAYOUT', 2.3676),
        ('DRAWING', 2.1985),
        ('NEW TANK AREA', 1.3863),
        ('TANK AREA', 1.3863),
        ('1', 1.0986),
        ('RACK AREA', 1.0986),
        ('NEW TANK', 1.0397),
    ),
    'DSL': (
        ('LINE DIAGRAM', 2.7081),
        ('SINGLE', 2.7081),
        ('SINGLE LINE', 2.7081),
        ('SINGLE LINE DIAGRAM', 2.7081),
        ('DIAGRAM 16', 2.6391),
        ('DIAGRAM 16 01', 2.6391),
        ('LINE DIAGRAM 16', 2.6391),
        ('NO', 2.1442),
        ('NO 4', 2.1442),
        ('SUBSTATION NO', 2.1442),
    ),
    'DWG': (
        ('TYPICAL', 1.2876),
        ('3D MODEL DESIGN', 1.0986),
        ('6', 1.0986),
        ('AREA/MODEL', 1.0986),
        ('AREA/MODEL INDEX', 1.0986),
        ('AREA/MODEL INDEX DRAWING', 1.0986),
        ('DESIGN AREA/MODEL', 1.0986),
        ('DESIGN AREA/MODEL INDEX', 1.0986),
        ('INDEX DRAWING', 1.0986),
        ('MODEL DESIGN', 1.0986),
    ),
    'LST': (
        ('LIST', 2.3026),
        ('I/O', 1.0986),
        ('I/O LIST', 1.0986),
    ),
    'MSD': (
        ('MATERIAL SELECTION DIAGRAM', 1.7918),
        ('SELECTION DIAGRAM', 1.7918),
        ('MATERIAL SELECTION', 1.4931),
        ('SELECTION', 1.4931),
        ('SELECTION DIAGRAM WATER', 1.0986),
    ),
    'PFD': (
        ('FLOW DIAGRAM', 1.7918),
        ('UTILITY FLOW', 1.3863),
        ('UTILITY FLOW DIAGRAM', 1.3863),
        ('FLOW DIAGRAM WATER', 1.0986),
        ('PROCESS FLOW', 1.0986),
        ('PROCESS FLOW DIAGRAM', 1.0986),
    ),
    'PID': (
        ('& INSTRUMENT', 3.2189),
        ('& INSTRUMENT DIAGRAM', 3.2189),
        ('INSTRUMENT DIAGRAM', 3.2189),
        ('PIPING &', 3.2189),
        ('PIPING & INSTRUMENT', 3.2189),
        ('INSTRUMENT', 2.341),
        ('INSTRUMENT DIAGRAM WATER', 1.9459),
        ('DISTRIBUTION', 1.7918),
        ('AIR', 1.3863),
        ('AIR DISTRIBUTION', 1.3863),
    ),
    'REP': (
        ('REPORT', 2.9992),
        ('CLOSE', 1.7918),
        ('CLOSE OUT', 1.7918),
        ('CLOSE OUT REPORT', 1.7918),
        ('OUT', 1.7918),
        ('OUT REPORT', 1.7918),
        ('REVIEW', 1.6679),
        ('ANALYSIS', 1.6094),
        ('ANALYSIS REPORT', 1.6094),
        ('REVIEW REPORT', 1.6094),
    ),
    'REQ': (
        ('MATERIAL REQUISITION', 2.4849),
        ('REQUISITION', 2.4849),
    ),
    'SCH': (
        ('CABLE SCHEDULE', 1.0986),
        ('SCHEDULE', 0.8318),
    ),
    'SPC': (
        ('SPECIFICATION', 3.0445),
        ('INSTRUMENT INSTALLATION', 1.0986),
        ('BULK', 0.7324),
    ),
    'STD': (
        ('INSTALLATION STANDARDS', 1.3863),
        ('STANDARDS', 1.3863),
    ),
}
