"""Generated by ``learn-type-discipline``. Do not edit by hand.

Source: input/classified_csv/**/*.csv
Generated: 2026-06-05T06:57:13Z
Majority floor: 70%; min occurrences: 4

Ambiguous types (no clear majority -- not emitted):
  CAL: top dest_id=1 share=67% of 21 rows
  DAL: top dest_id=1 share=33% of 27 rows
  DAS: top dest_id=13 share=39% of 31 rows
  DWG: top dest_id=13 share=39% of 31 rows
  LST: top dest_id=13 share=29% of 14 rows
  MTO: top dest_id=4 share=50% of 8 rows
  PHL: top dest_id=25 share=25% of 4 rows
  REP: top dest_id=25 share=34% of 38 rows
  REQ: top dest_id=13 share=56% of 36 rows
  SCH: top dest_id=4 share=40% of 10 rows
  SPC: top dest_id=4 share=28% of 25 rows
  STD: top dest_id=1 share=33% of 9 rows
"""
from __future__ import annotations

# Each entry: type -> (dest_discipline_id, share, support_count)
# share and support_count are informational; only dest_id is used at classify time.
TYPE_TO_DISCIPLINE: dict[str, int] = {
    'DBD': 4,  # 100% of 5 rows
    'DGA': 13,  # 93% of 27 rows
    'DSL': 4,  # 100% of 7 rows
    'MSD': 17,  # 100% of 5 rows
    'PFD': 17,  # 100% of 5 rows
    'PID': 17,  # 96% of 25 rows
    'PLN': 26,  # 78% of 9 rows
    'PRO': 26,  # 100% of 66 rows
    'PSF': 17,  # 100% of 4 rows
}
