"""Generated by ``learn-type-discipline``. Do not edit by hand.

Source: input/classified_csv/**/*.csv
Generated: 2026-05-25T06:44:17Z
Majority floor: 70%; min occurrences: 4

Ambiguous types (no clear majority -- not emitted):
  CAL: top dest_id=1 share=67% of 21 rows
  DAL: top dest_id=4 share=43% of 21 rows
  DAS: top dest_id=4 share=62% of 26 rows
  DWG: top dest_id=4 share=56% of 27 rows
  LST: top dest_id=4 share=60% of 10 rows
  SCH: top dest_id=4 share=67% of 6 rows
  STD: top dest_id=4 share=62% of 8 rows
"""
from __future__ import annotations

# Each entry: type -> (dest_discipline_id, share, support_count)
# share and support_count are informational; only dest_id is used at classify time.
TYPE_TO_DISCIPLINE: dict[str, int] = {
    'DBD': 4,  # 100% of 5 rows
    'DGA': 4,  # 100% of 27 rows
    'DSL': 4,  # 100% of 7 rows
    'MTO': 4,  # 88% of 8 rows
    'REP': 4,  # 73% of 15 rows
    'REQ': 4,  # 74% of 34 rows
    'SPC': 4,  # 70% of 20 rows
}
