"""Generated by ``learn-type-discipline``. Do not edit by hand.

Source: input/classified_csv/**/*.csv
Generated: 2026-05-25T07:56:33Z
Majority floor: 70%; min occurrences: 4

Ambiguous types (no clear majority -- not emitted):
  CAL: top dest_id=1 share=67% of 21 rows
  DAL: top dest_id=4 share=37% of 27 rows
  DAS: top dest_id=4 share=52% of 31 rows
  DWG: top dest_id=4 share=48% of 31 rows
  LST: top dest_id=4 share=50% of 14 rows
  PHL: top dest_id=11 share=50% of 4 rows
  REP: top dest_id=11 share=50% of 38 rows
  REQ: top dest_id=4 share=69% of 36 rows
  SPC: top dest_id=4 share=68% of 25 rows
  STD: top dest_id=4 share=67% of 9 rows
"""
from __future__ import annotations

# Each entry: type -> (dest_discipline_id, share, support_count)
# share and support_count are informational; only dest_id is used at classify time.
TYPE_TO_DISCIPLINE: dict[str, int] = {
    'DBD': 4,  # 100% of 5 rows
    'DGA': 4,  # 100% of 27 rows
    'DSL': 4,  # 100% of 7 rows
    'MSD': 11,  # 100% of 5 rows
    'MTO': 4,  # 88% of 8 rows
    'PFD': 11,  # 100% of 5 rows
    'PID': 11,  # 100% of 25 rows
    'PLN': 4,  # 78% of 9 rows
    'PRO': 4,  # 100% of 66 rows
    'PSF': 11,  # 100% of 4 rows
    'SCH': 4,  # 70% of 10 rows
}
