"""Generated by ``learn-type-keywords``. Do not edit by hand.

Source: input/classified_csv/**/*.csv
Generated: 2026-05-16T21:06:30Z
Training rows used: 256

Untrained types (< 4 examples, no rules emitted):
  BOD (2), BOM (1), DBD (2), DCE (2), DHZ (1), DPP (3), DSD (3), DWD (1), IDX (1), MTO (2), PHL (3), PLN (1), PRO (3), PSF (3), REG (1), SOW (2)
"""
from __future__ import annotations

UNTRAINED_TYPES: frozenset[str] = frozenset({
    'BOD',
    'BOM',
    'DBD',
    'DCE',
    'DHZ',
    'DPP',
    'DSD',
    'DWD',
    'IDX',
    'MTO',
    'PHL',
    'PLN',
    'PRO',
    'PSF',
    'REG',
    'SOW',
})

TYPE_KEYWORD_RULES: dict[str, tuple[tuple[str, float], ...]] = {
    'CAL': (
        ('CALCULATION', 1.9459),
        ('CALCULATION NOTE', 1.0986),
        ('NOTE', 1.0986),
        ('STRUCTURAL CALCULATION', 1.0986),
        ('STRUCTURAL CALCULATION NOTE', 1.0986),
    ),
    'DAL': (
        ('LAYOUT AREA', 2.3026),
        ('STEEL STRUCTURE', 2.1972),
        ('STRUCTURE', 2.1972),
        ('LAYOUT', 2.0923),
        ('STEEL', 2.0723),
        ('ARRANGEMENT', 1.9459),
        ('ARRANGEMENT LAYOUT', 1.9459),
        ('ARRANGEMENT LAYOUT AREA', 1.9459),
        ('CIVIL GENERAL', 1.9459),
        ('CIVIL GENERAL ARRANGEMENT', 1.9459),
    ),
    'DAS': (
        ('DATA', 3.1738),
        ('DATA SHEET', 3.1738),
        ('SHEET', 3.1024),
        ('ELECTRICAL DATA', 1.3863),
        ('ELECTRICAL DATA SHEET', 1.3863),
        ('PRESSURE', 1.3863),
        ('GAUGES', 1.0986),
        ('MECHANICAL DATA', 1.0986),
        ('MECHANICAL DATA SHEET', 1.0986),
        ('PRESSURE GAUGES', 1.0986),
    ),
    'DGA': (
        ('LAYOUT DRAWING', 2.5649),
        ('PIPING LAYOUT DRAWING', 2.5649),
        ('PIPING LAYOUT', 2.3676),
        ('DRAWING', 1.8106),
        ('NEW TANK AREA', 1.3863),
        ('TANK AREA', 1.3863),
        ('RACK AREA', 1.0986),
        ('NEW TANK', 1.0397),
    ),
    'DSL': (
        ('LINE DIAGRAM', 2.7081),
        ('SINGLE', 2.7081),
        ('SINGLE LINE', 2.7081),
        ('SINGLE LINE DIAGRAM', 2.7081),
        ('NO', 2.1442),
        ('SUBSTATION NO', 2.1442),
        ('LINE', 2.1063),
        ('HSWG', 1.9459),
        ('SUBSTATION', 1.8057),
        ('MSWG', 1.3863),
    ),
    'DWG': (
        ('TYPICAL', 1.2876),
        ('AREA/MODEL', 1.0986),
        ('AREA/MODEL INDEX', 1.0986),
        ('AREA/MODEL INDEX DRAWING', 1.0986),
        ('DESIGN AREA/MODEL', 1.0986),
        ('DESIGN AREA/MODEL INDEX', 1.0986),
        ('INDEX DRAWING', 1.0986),
        ('MODEL DESIGN', 1.0986),
        ('MODEL DESIGN AREA/MODEL', 1.0986),
        ('PIPE SUPPORT', 1.0986),
    ),
    'LST': (
        ('LIST', 2.3026),
        ('I/O', 1.0986),
        ('I/O LIST', 1.0986),
    ),
    'MSD': (
        ('MATERIAL SELECTION DIAGRAM', 1.7918),
        ('SELECTION DIAGRAM', 1.7918),
        ('MATERIAL SELECTION', 1.4931),
        ('SELECTION', 1.4931),
        ('SELECTION DIAGRAM WATER', 1.0986),
    ),
    'PFD': (
        ('FLOW DIAGRAM', 1.7918),
        ('UTILITY FLOW', 1.3863),
        ('UTILITY FLOW DIAGRAM', 1.3863),
        ('FLOW DIAGRAM WATER', 1.0986),
        ('PROCESS FLOW', 1.0986),
        ('PROCESS FLOW DIAGRAM', 1.0986),
    ),
    'PID': (
        ('INSTRUMENT DIAGRAM', 3.2189),
        ('PIPING & INSTRUMENT', 3.2189),
        ('INSTRUMENT', 2.341),
        ('INSTRUMENT DIAGRAM WATER', 1.9459),
        ('DISTRIBUTION', 1.7918),
        ('AIR', 1.3863),
        ('AIR DISTRIBUTION', 1.3863),
        ('DIAGRAM WATER DISPOSAL', 1.2973),
        ('COLLECTION', 1.0986),
        ('DIAGRAM INSTRUMENT', 1.0986),
    ),
    'REP': (
        ('REPORT', 2.9992),
        ('CLOSE', 1.7918),
        ('CLOSE OUT', 1.7918),
        ('CLOSE OUT REPORT', 1.7918),
        ('OUT', 1.7918),
        ('OUT REPORT', 1.7918),
        ('REVIEW', 1.6679),
        ('ANALYSIS', 1.6094),
        ('ANALYSIS REPORT', 1.6094),
        ('REVIEW REPORT', 1.6094),
    ),
    'REQ': (
        ('MATERIAL REQUISITION', 2.4849),
        ('REQUISITION', 2.4849),
    ),
    'SCH': (
        ('CABLE SCHEDULE', 1.0986),
        ('SCHEDULE', 0.8318),
    ),
    'SPC': (
        ('SPECIFICATION', 3.0445),
        ('INSTRUMENT INSTALLATION', 1.0986),
        ('BULK', 0.7324),
    ),
    'STD': (
        ('STANDARD', 1.6094),
        ('INSTALLATION STANDARD', 1.3863),
    ),
}
