"""One-off: refresh output/_mapping_data.json bucket maps + stats + samples
from the live config and the current documents_updated.csv, then emit a
Markdown report. Not a permanent tool — run from the repo root:

    .venv\\Scripts\\python scripts\\_update_mapping.py
"""
from __future__ import annotations

import csv
import json
from collections import Counter
from pathlib import Path

# Live config (source of truth for the bucket maps).
from classifier.config.buckets import (
    BUCKET_TO_CLASS, TYPE_TO_BUCKET, BUCKET_PRIMARY_CODE,
)
from classifier.pipeline.classify_titles import classify_titles

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "output" / "_mapping_data.json"
CSV_PATH = ROOT / "output" / "documents_updated.csv"
REPORT_PATH = ROOT / "output" / "mapping_report.md"

csv.field_size_limit(10 ** 7)


def load_rows() -> list[dict]:
    with CSV_PATH.open(encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def update_json(data: dict, rows: list[dict]) -> dict:
    # --- bucket maps straight from the live config ---
    data["type_to_bucket"] = dict(TYPE_TO_BUCKET)
    data["bucket_to_class"] = dict(BUCKET_TO_CLASS)
    data["bucket_primary_code"] = dict(BUCKET_PRIMARY_CODE)

    # --- stats recomputed from the current CSV ---
    doc_type_dist = Counter((r.get("doc_type") or "").strip() for r in rows)
    type_dist = Counter((r.get("type") or "").strip() for r in rows)
    disc_dist = Counter((r.get("discipline_id") or "").strip() for r in rows)
    data["stats"] = {
        "total_rows": len(rows),
        "doc_type_dist": dict(doc_type_dist.most_common()),
        "type_dist": dict(type_dist.most_common()),
        "discipline_dist": dict(disc_dist.most_common()),
    }

    # --- samples re-classified by the current title-only classifier ---
    titles = [s["title"] for s in data.get("samples", [])]
    if titles:
        res = classify_titles([{"title": t} for t in titles])
        data["samples"] = [
            {
                "title": t,
                "doc_type": r["doc_type"],
                "type": r["type"],
                "discipline_id": "" if r["discipline_id"] is None else str(r["discipline_id"]),
            }
            for t, r in zip(titles, res)
        ]
    return data


def _bar(n: int, total: int, width: int = 30) -> str:
    fill = 0 if total == 0 else round(width * n / total)
    return "#" * fill + "." * (width - fill)


def write_report(data: dict) -> None:
    disc_name = {d["id"]: d["name"] for d in data.get("disciplines", [])}
    stats = data["stats"]
    total = stats["total_rows"]
    lines: list[str] = []
    out = lines.append

    out("# Classifier mapping report\n")
    out(f"Source: `output/documents_updated.csv` ({total} rows). "
        "Generated by `scripts/_update_mapping.py`.\n")

    # doc_type distribution
    out("## doc_type distribution\n")
    out("| class | count | share | |")
    out("|---|---:|---:|---|")
    for k, n in stats["doc_type_dist"].items():
        label = k or "(empty)"
        out(f"| {label} | {n} | {n/total:.0%} | `{_bar(n, total)}` |")
    out("")

    # bucket -> class fold
    out("## Bucket → class fold\n")
    out("| bucket | class | primary code |")
    out("|---|---|---|")
    for b, cls in data["bucket_to_class"].items():
        out(f"| {b} | {cls} | {data['bucket_primary_code'].get(b, '')} |")
    out("")

    # type -> bucket -> class
    out("## Type → bucket → class\n")
    out("| type | bucket | class |")
    out("|---|---|---|")
    for ty, bucket in sorted(data["type_to_bucket"].items()):
        out(f"| {ty} | {bucket} | {data['bucket_to_class'].get(bucket, '')} |")
    out("")

    # type distribution
    out("## Type distribution\n")
    out("| type | count |")
    out("|---|---:|")
    for k, n in stats["type_dist"].items():
        out(f"| {k or '(empty)'} | {n} |")
    out("")

    # discipline distribution
    out("## Discipline distribution\n")
    out("| id | discipline | count |")
    out("|---|---|---:|")
    for k, n in stats["discipline_dist"].items():
        out(f"| {k or '(empty)'} | {disc_name.get(k, '')} | {n} |")
    out("")

    # samples
    out("## Sample classifications\n")
    out("| title | doc_type | type | discipline |")
    out("|---|---|---|---|")
    for s in data.get("samples", []):
        out(f"| {s['title']} | {s['doc_type']} | {s['type'] or ''} | "
            f"{disc_name.get(s['discipline_id'], s['discipline_id'])} |")
    out("")

    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    rows = load_rows()
    data = update_json(data, rows)
    JSON_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                         encoding="utf-8")
    write_report(data)
    print(f"updated {JSON_PATH.name}; wrote {REPORT_PATH.name}")
    print("doc_type_dist:", data["stats"]["doc_type_dist"])


if __name__ == "__main__":
    main()
